# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbe9319aa531f58cf8813e254c056f04117ea9e218a2da53cd573c6aea5c98bdfeb215fde08998d3002cf3af1a4ba726052360536a7e87b546944858ec0b41e2

test:
  secret_key_base: 410012a29229aceacb7078fe011e39eb46d7cd028bc045dfec2a7e960521e484f194746fd914a996add4dfb4c3968c9f4108d91c09377109e6d057bbcc481011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
